language: python
python:
  - '2.7'
before_install:
  - 'sudo apt-get install $(grep -vE "^\s*#" package_list.txt  | tr "\n" " ")'
  - 'sudo apt-get install python-numpy-dev'
  - 'sudo apt-get install python-scipy'
  - 'sudo apt-get install python-matplotlib'
  - 'virtualenv willsenv --system-site-pacages'
  - 'source bin/activate'
  - 'pip --version'
install:
  - 'pip install pandas --quiet'
  - 'pip install celery --quiet'
  - 'pip install biopython --quiet'
  - 'pip install scikit-learn --quiet'
  - 'chmod +x ./FastTree'
  - 'sudo Rscript install_R_packages.R'
  - 'pip install -r requirements.txt --use-mirrors'
script: 'nosetests -v'
cache: bundler